### PR TITLE
Updated function with fastest implementation

### PR DESCRIPTION
**Pull request by cartersgenes**
see http://jsperf.com/count-the-number-of-characters-in-a-string for perf data

### CODE REVIEW

**Comment by stoeffel** [comment]
You should readd the deleted lines 4-7 to fix the failing tests.

**Comment by stoeffel** [comment]
I can confirm that with your change it is faster :ok_hand: 
Our current implementation:
```
$ gulp bench -f count
[18:29:03] Running benchmark count [/Users/stoeffel/src/underscore.string/master/bench/count.js]...
[18:29:09] count x 5,987,433 ops/sec ±1.01% (100 runs sampled)
```

With your change:

```
$ gulp bench -f count
[18:30:01] Running benchmark count [/Users/stoeffel/src/underscore.string/master/bench/count.js]...
[18:30:07] count x 12,897,697 ops/sec ±0.58% (100 runs sampled)
```

**Comment by stoeffel** [comment]
@cartersgenes Could you update your PR? Thanks

**Comment by cartersgenes** [comment]
Ive added those lines... let me know if there's anything else

**Comment by stoeffel** [comment]
@cartersgenes :+1: thanks

**Pull request merged**
