### PR TITLE
Official Meteor integration

### PR DESCRIPTION
**Pull request by splendido**
Hello guys,

As you might know, the [Meteor](https://www.meteor.com/) community is heavily using underscore.string. We have many different [wrapper packages](https://atmospherejs.com/?q=underscore%20string) all doing almost the same thing but not all of them kept updated, so I'm submitting a PR that integrates Meteor packaging directly into your repository: at the end of this merge process, in case you'll find yourself comfortable with it, we'll get automated new Meteor package releases with every new release of underscore.string.

I've made this PR as lean as possible so as not to take up too much space within your repository: basically it adds only a `package.js` file among the ones already present for other package managers.

All you have to do after accepting this PR would be:

1. Create an account at https://meteor.com/ (click SIGN IN, then Create account). After you've done that, please let me know the name of the account, and we'll add you as a maintainer of the *underscorestring* organization (which has been already reserved to make things simpler for you).

2. Head to [autopublish.meteor.com](http://autopublish.meteor.com/), sign in with your GitHub account, locate this repository and enable it for autopublish by toggling the checkbox you'll find on the right side of the repository item. You can get an idea about how Meteor Autopublish works by having a quick look at [this page](http://autopublish.meteor.com/howitworks), but basically it creates a [web hook](https://help.github.com/articles/about-webhooks/) to let us know when you push new tags. When you'll release new versions, autopublish.meteor.com will automatically package the the new version of the library also for Meteor!

3. In case you're not comfortable with autopublish.meteor.com maintaining access rights to your repos, please head to [GitHub Application Settings](https://github.com/settings/applications) and revoke permissions for *Meteor Autopublish*.

Please note that you will not be able to toggle your repository until you'll have the `package.js` file on your master branch.

Please also note that we've already published the current version of the package on [Atmosphere](https://atmospherejs.com/underscorestring/underscore.string) (Meteor's package directory) under the name `underscorestring:underscore.string`. If you think another name would be a better fit, just let us know!

Thanks in advance for your availability and collaboration and congratulation for the awesome project!
Luca & the [Meteor Packaging Team](https://github.com/orgs/MeteorPackaging/people)

### CODE REVIEW

**Comment by stoeffel** [comment]
This sounds good to me.
I think if we add official meteor support, we should describe it in the `README.md`.
Could you add something like ["Usage in nodejs and browserify"](https://github.com/epeli/underscore.string/#in-nodejs-and-browserify) to the `README.md`?

And could you squash your commits to one so we can easily cherry-pick to test it?

Thanks for the PR.

**Comment by splendido** [comment]
Yeah, sorry I've forgot to consider the `README`: also I'm noticing now it's `README.markdown` and not `README.md` so there's another line to change in `package.js`.

I'll try to make this with one single commit.

Tnx!

**Comment by stoeffel** [comment]
Thanks!

**Comment by splendido** [comment]
Ok, I've managed to make it worst...
I'll try to do all this on a new branch, and create a new PR!
Is this fine?

**Comment by stoeffel** [comment]
You could also just squash the commits (http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by splendido** [comment]
Ok, done with #405

**Pull request closed without merging**
