### PR TITLE
proposal for moving to mocha

### PR DESCRIPTION
**Pull request by stoeffel**
How about we move from qunit to mocha.
This would clean up our repo and allow us to have a nice code coverage report.

As an example I migrated some tests in the `tests` folder and created a new gulp task (`gulp mocha`).

screen shot 2015-02-17 at 18 49 08

# TODO

- [x] migrate all tests
- [x] migrate standalone tests
- [x] remove qunit
- [x] remove old tests
- [x] moved benchmark to benchmark.js

### CODE REVIEW

**Comment by epeli** [comment]
:heart: Mocha!

**Comment by stoeffel** [comment]
Sweet then I will migrate the rest. This will take some time though.

**Comment by stoeffel** [comment]
I migrated all tests, but it needs some review to make sure I didn't miss a test or misspelled something.
Detailed coverage is in `./coverage/index.html` or run `gulp test --cov`.

**Comment by stoeffel** [comment]
@epeli do you prefer a mocha reporter? I would vote for "nyan" :smile: or "dot"

screen shot 2015-02-18 at 13 24 18

**Comment by stoeffel** [comment]
@epeli  If you have time, it would be cool if you could review this, it's a really big change :smile:

**Comment by epeli** [comment]
> it's a really big change

Yeah, that's why I've been fine with qunit =) But I'll take a look at during the weekend.

**Comment by stoeffel** [comment]
@epeli did you have time to check this out?

**Comment by stoeffel** [comment]
@epeli Would be cool if we could merge or close this to not block further development.

**Pull request merged**
