### PR TITLE
Add header to the minified build file featuring package name, version…

### LINKED ISSUE #432: Add header info to the bundled files
It'd be pretty useful if the library name, version and such info was prepended to the bundled `underscore.string.js` and `underscore.string.min.js` files.

### PR DESCRIPTION
**Pull request by mondalaci**
… and homepage URL. Resolves #432.

### CODE REVIEW

**Comment by stoeffel** [comment]
How about adding `package.license` as well and adding the header as one line in a block comment.
Like i.e. jquery

```js
/*! jQuery v1.11.3 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/license */
!function(a,b){
```

and could you add the header to the uncompressed file as well.

Thanks.

**Comment by stoeffel** [comment]
@mondalaci :bell:

**Comment by mondalaci** [comment]
@stoeffel No worries, I'm a zero inbox guy so I don't forget stuff. I've had to a lot of work to do but I've updated this PR in the meantime as you suggested.

Now the header looks like:

`// underscore.string 3.1.1 | MIT licensed | http://epeli.github.com/underscore.string/`

followed by a newline which separates it from the actual source code. Tried it without the separating newline but it didn't look so appealing.

Also, I'd rather use a singe line comment instead of a block level comment. A block level comment adds extra characters without any advantages.

**Comment by stoeffel** [comment]
Thanks for the changes. The header looks nice now. But I still would prefer
a blockcomment. There is one advantage with blockcomments. When someone
concatinates all files in his buildprocess it could happen that the
linebreak after the linecomment gets deleted and the hole thing gets
commented. And two characters more don't add up much :smiley:
Am 27.06.2015 02:25 schrieb "László Monda" <notifications@github.com>:

**Comment by mondalaci** [comment]
@stoeffel All right, well reasoned. :) Updated my PR.

**Comment by stoeffel** [comment]
Nice. Thanks a lot.

**Pull request merged**
