### PR TITLE
new and simpler build workflow

### LINKED ISSUE #478: Use npmcdn.com instead of commiting build artifacts into git
Keeping build artifacts in git is bad for so many reasons...

To do this we can just remove the `dist` from git and create it on npm prepublish hook.

Old school users can then just download the bundle from 

https://npmcdn.com/underscore.string@3.2.2/dist/underscore.string.min.js

or even stick it to script tag directly.

### PR DESCRIPTION
**Pull request by stoeffel**
This removes gulp completely. I will do the same for the gh-pages branch if you like.
As you can see to release we just need to update the changelog and the version in the package.json and then run `npm run release`.
This will allow use to have a much shorter release cycle (it's a pain atm to publish a new version).

It also removes the build artefacts from the repo and links to npmcdn.
The built artefacts are directly in the root of the module (after publishing).
And it removes some eslint issues :smile_cat: 
closes #478

I will have to check this again tomorrow, have to sleep first.
@epeli would be cool if you could review this.

### CODE REVIEW

**Comment by stoeffel** [comment]
wow you are fast :smile:

**Comment by epeli** [comment]
Just realized: Do we break Bower if we remove `dist`?

**Comment by stoeffel** [comment]
> Just realized: Do we break Bower if we remove dist?

could be. It's a long time since I last used bower :laughing:

**Comment by epeli** [comment]
Yeah. I haven't ever used it or personally know anybody using it.

**Comment by stoeffel** [comment]
I guess we need to add it to support bower.

**Comment by epeli** [comment]
Meteor might require it too. Component seems to be dead https://github.com/componentjs/component#this-project-is-deprecated

**Comment by stoeffel** [comment]
I added `dist` again

**Comment by stoeffel** [comment]
Sorry. Will have to sleep now.
Feel free to commit and change every thing.

**Comment by stoeffel** [comment]
@splendido do you know if meteor needs the build artefacts in the repo?

**Comment by stoeffel** [comment]
@epeli any input on this and #482. I think we have to keep `dist` in the repo for now.

**Comment by splendido** [comment]
@stoeffel what do you mean with 'build artefacts'?
...any file created by 'meteor publish' can be safely removed

**Comment by stoeffel** [comment]
@splendido by build-artefacts I mean every thing in the `dist` folder.

**Comment by splendido** [comment]
I see.
Well, if you like to continue with autopublish the answer is yes: at the time of running `meteor publish` the file `dist/underscore.string.js` must be there (see [this line](https://github.com/epeli/underscore.string/blob/master/package.js#L14)).

But if you could publish by hands you'd only need that file when running `meteor publish` which means you could build the project, publish it for Meteor and then clean up everything.

**Comment by stoeffel** [comment]
Okay. Thanks for your help. I think we should just keep the dist in the repo. Makes it easier to support meteor and bower needs it anyway.

**Comment by stoeffel** [comment]
@epeli. I think this and #482 is good to go. Do you have some time this week or next to review. I think this will speed up our release cycle. Currently it's a bit of a pain.

**Comment by stoeffel** [comment]
I will merge on Monday and will release a new version (and include some bug fix PRs.)

**Comment by stoeffel** [comment]
> rebased ans squashed

Will do a last review this afternoon or tomorrow and then merge and publish a patch release.

// cc @epeli any objections?

**Comment by cahrens** [comment]
@stoeffel Are you still planning to publish a patch release soon?

**Comment by stoeffel** [comment]
> @stoeffel Are you still planning to publish a patch release soon?

Totally, sorry for the delay. I had to take care of my baby daughter today. I will definitely work on it tomorrow.
The new build chain should allow us to publish faster.

**Comment by cahrens** [comment]
No problem-- just curious about the timeframe. Thanks for the information!

**Pull request merged**
