### PR TITLE
add dedent function

### LINKED ISSUE #46: indent and dedent?
Have you considered adding indent and dedent to your library?

### PR DESCRIPTION
**Pull request by stoeffel**
closes #46

### CODE REVIEW

**Comment by sindresorhus** [comment]
:+1:

**Comment by stoeffel** [comment]
@epeli any input on this?

**Comment by epeli** [comment]
The use case I see for this is following:

```js
class Command {

    getHelpString() {
        // ES6 template string
        return dedent(`
            Foo bar baz

            command [options] <args..>

        `);
    }
}
```

and it should remove the common leading white space and nothing else. Like in Python https://docs.python.org/2/library/textwrap.html#textwrap.dedent

So

> Do you think that dedent with a pattern should also only dedent if the hole block is indented?

yes.

**Comment by stoeffel** [comment]
> Do you think that dedent with a pattern should also only dedent if the hole block is indented?
yes.

Done :bowtie:

**Comment by stoeffel** [comment]
In my opinion this is ready to be merged. Any thing to add?

**Comment by epeli** [comment]
nope

**Pull request merged**
