### PR TITLE
Fixed capitalize not converting the rest of the string to lowercase

### PR DESCRIPTION
**Pull request by abdulsattar**
Capitalize (according to Wikipedia and the Ruby String#capitalize) converts the
first letter to uppercase and the rest to lowercase. Implementation in this
library didn't convert the remainder to lowercase.

http://ruby-doc.org/core-2.0.0/String.html#method-i-capitalize
http://en.wikipedia.org/wiki/Capitalization

### CODE REVIEW

**Comment by ricardograca** [comment]
How about implementing this for the next not-backwards-compatible version?

**Comment by stoeffel** [comment]
As said before:

> I feel like this would break a lot of existing code. Perhaps _capitalize(str.toLowerCase()) is a better way to achieve this result

even in a not-backwards-compatible version I'm not sure if it's a good idea to change it.
I think opinions differ if `capitalize` should lowercase the rest of the string. 
IMHO `capitalize(str.toLowerCase())` is convenient enough.

**Comment by stoeffel** [comment]
Maybe a flag would be an option, but I still would prefer to not change it.

**Comment by ricardograca** [comment]
I know that it has the potential to break existing code, but we don't know how much. That's why breaking version numbers were invented ;)

I think it's easy enough to implement an option that will make existing code work fine and will allow this library to be even more useful. It's kind of awkward having a supposedly "String manipulation" library and still needing to hack a solution for a common use case.

**Comment by stoeffel** [comment]
> That's why breaking version numbers were invented ;)

true :smile: 

I think I could live with a flag. 
@epeli are you :+1: on a flag?

**Comment by epeli** [comment]
flag is cool

**Comment by stoeffel** [comment]
@ricardograca do you want to make a pr?

**Comment by romanbsd** [comment]
BTW, I observed two distinct teams working with Backbone, where developers patched this method, because it was impossible to use the original (IMHO broken) version.

**Comment by ricardograca** [comment]
@stoeffel Sure. Seems simple enough. I'm going to use the same format as camelize for consistency:

> capitalize(string, [lowercaseRemaining=false]) => string

I'm not too sure about the flag name though. If anyone has a better suggestion I would appreciate it.

**Comment by stoeffel** [comment]
> same format as camelize for consistency

:+1: 

> If anyone has a better suggestion

How about `lowercaseRest` or just `lowercase`?

**Comment by ricardograca** [comment]
Stupid question:

What are "build artifacts in the dist directory"? I noticed that the files in that dir were automatically updated, probably when I ran the tests. So, should I commit those changes as well or not?

**Comment by stoeffel** [comment]
No don't commit files from the dist folder. We will build them when we create a new release.

**Pull request closed without merging**
