### PR TITLE
Add support for ß in clean diacritics

### PR DESCRIPTION
**Pull request by alarie**

### CODE REVIEW

**Comment by epeli** [comment]
Do not commit build artifacts. Please read [CONTRIBUTING](https://github.com/epeli/underscore.string/blob/master/CONTRIBUTING.markdown#contributing).

Btw I found weird behavior on Chrome when calling `"ß".toUpperCase()`. It evaluates to `SS` and then `"ß".toUpperCase().toLowerCase()` is `ss`. Any ideas why this happens?

**Comment by alarie** [comment]
Sorry, I removed the dist-files from the commit.

I didn't know of the transformation happening in Chrome. But it is actually correct. There is no capital "ß", so convention (in Germany at least) is to replace it with "SS". Firefox on the other hand just keeps the "ß".

**Comment by stoeffel** [comment]
Arg, one more thing that is inconsistent between browsers.

**Comment by stoeffel** [comment]
Could you squash your commits to one? Otherwise this LGTM. Thx for the PR

**Comment by epeli** [comment]
Thanks

**Pull request merged**
