### PR TITLE
Add map method: Creates a new string with the results of calling a pr…

### PR DESCRIPTION
**Pull request by keropodium**
…ovided function on every character of the given string.

Here is my proposal for a function I found usefull for writing out an AngularJS model parser. Tell me what you think about it.

### CODE REVIEW

**Comment by epeli** [comment]
`String#replace` can be used for this too

```js
"Hello World".replace(/./g, c => c === 'o' ? 'O' : c)
// "HellO WOrld"
```

**Comment by stoeffel** [comment]
I think adding a map would be confusing for users. Since most are used to use a map function on an array and not on a string. And like @epeli said you can use replace or if you really want to map each char you could do.
`string.split('').map(func).join()`

**Comment by keropodium** [comment]
@epeli Great hack, the simpler the better, even [outperforms](http://jsperf.com/array-prototype-map-vs-string-prototype-replace) my solution.

@stoeffel If you think a map function would be confusing for users considering this is string manipulation library, maybe you don't trust them very much.

Still you have to check if the type of the given input is a string and maybe convert it. Encapsulating this logic inside a function feels better. Anyways, your choice, we can close this pull request. :smiley:

**Comment by stoeffel** [comment]
> If you think a map function would be confusing for users considering this is string manipulation library, maybe you don't trust them very much.

Yes, it's a string manipulation lib, but if you have this:

```js
import map from 'underscore.string/map';

// ... 100 lines of code

map(foo, func);

arr.map(func2);
```
It's not clear that `map` maps each char. But we could simple rename `map` to `mapChar` to clarify it.

**Comment by epeli** [comment]
> @epeli Great hack, the simpler the better, even outperforms my solution.

Maybe this should be implemented using it.

> But we could simple rename map to mapChar to clarify it.

User can itself decide the name in the import, but that's a good point anyway. In the `index.js` the `map` name is fine again.

Also `map` collides with Underscore.js and it should be added here https://github.com/epeli/underscore.string/blob/master/exports.js#L5 

This is bit out of topic but this make me think whether we should alias all colliding methods with `string` suffixes / prefixes. That way they would be accessible as Underscore.js mixins again.

**Comment by keropodium** [comment]
Updated using your advices.

@epeli I preferred renaming it to `mapChars` to avoid collisions and better clarification as @stoeffel stated.

**Comment by epeli** [comment]
> @epeli I preferred renaming it to mapChars to avoid collisions and better clarification as @stoeffel stated.

Hmm. It's now inconsistent with include, contains, reverse and join which have the exact same concern about the naming and we can't change the names for those without breaking backwards compact so I think prefer just `map` and aliasing it with mapChars in index.js.

**Comment by keropodium** [comment]
>Hmm. It's now inconsistent with include, contains, reverse and join which have the exact same concern about the naming and we can't change the names for those without breaking backwards compact so I think prefer just map and aliasing it as mapChars in index.js.

@epeli You mean something like...
```javascript
s.mapChars         = require('./map');`
```
In here? https://github.com/keropodium/underscore.string/blob/map/index.js#L79

**Comment by epeli** [comment]
Exactly.

**Comment by keropodium** [comment]
> Exactly.

@epeli Done.

**Comment by keropodium** [comment]
> Exactly.

@epeli Done.

**Pull request merged**
