### PR TITLE
new gh-page

### PR DESCRIPTION
**Pull request by stoeffel**
The new gh-page is more or less just the README rendered with bootstrap.

- render README using metalsmith
- add bootstrap
- add Rainbow.js to enable syntax highlighting
- move style.css to less
- add gulp tasks for building the page

***This PR should not be merged before 3.0 is released, because it works best with the new README structure.***

screen shot 2015-01-14 at 16 22 33

### CODE REVIEW

**Comment by epeli** [comment]
Looks good!

Is it possible to make functions docs linkable? Like github. Example https://github.com/epeli/underscore.string#cleanstring--string

**Comment by stoeffel** [comment]
> Is it possible to make functions docs linkable?

I will try.

**Comment by stoeffel** [comment]
screen shot 2015-01-14 at 17 44 55

Done

**Comment by epeli** [comment]
Rock!

**Pull request merged**
